services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: murodjon
      POSTGRES_PASSWORD: 1199
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-murodjon.mukhamadaliev@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-1199}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "80:80"
    networks:
      - postgres
    restart: unless-stopped
  networks:
    postgres:
      driver: bridge
    spring:
      driver: bridge

  volumes:
    postgres:
    pgadmin: