server:
  port: 9091

spring:
  application:
    name: notification
  datasource:
    username: postgres
    password: 1199
    url: jdbc:postgresql://localhost:5432/notification
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        hibernate:
    hibernate:
      ddl-auto: create
    show-sql: true
    eureka:


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

