server:
  port: 8081
spring:
  application:
    name: customer
  datasource:
    username: postgres
    password: 1199
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        hibernate:
    hibernate:
      ddl-auto: create
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 10





